name: app11_bitcoin_ticker
description: app11_bitcoin_ticker
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.19.0 <3.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.0.2
  intl: ^0.18.0
  google_fonts: ^4.0.1
  flutter_svg_provider: ^1.0.3
  http: ^0.13.5
  flutter_spinkit: ^5.1.0
  get: ^4.6.5
  sizer: ^2.0.15
  sidebarx: ^0.14.0
  animated_text_kit: ^4.2.2
  glassmorphism: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env

