name: app10_clima
description: app 10 - clima app
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.1
  flutter_svg_provider: ^1.0.3
  geolocator: ^8.2.1
  http: ^0.13.5
  flutter_spinkit: ^5.1.0
  get: ^4.6.5
  get_storage: ^2.0.3




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svg/

